config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  # Note the < means subclass of,
  # so in this case Article is a subclass of ActiveRecord::Base
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 3, maximum: 300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_action :set_article, only: [:update, :edit, :show, :destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end
  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = "Article was successfully created!"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

def update
  if @article.update(article_params)
    flash[:success] = "Article was successfully updated"
    redirect_to article_path(@article)
  else
    render 'edit'
  end
end

def edit
end

def show
end

def destroy
  @article.destroy
  flash[:danger] = "Article was successfully deleted"
  redirect_to articles_path
end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

  <div class='row'>
    <div class='col'>
      <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
      <% end %>
      <div class="col-sm-4">
        <%= link_to "Cancel request and return to articles listing", articles_path %>
      </div>
    </div>
  </div>

<!-- <form>
  <div class="form-group row">
    <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
    </div>
  </div>
  <div class="form-group row">
    <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
    </div>
  </div>
</form> -->

app/views/articles/edit.html.erb
<h1 align="center">Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<p><%= link_to "Create new article", new_article_path %></p>


<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>

  <% @articles.each do |article| %>
  <tr>
    <td> <%= article.title %> </td>
    <td> <%= article.description %> </td>
    <td> <%= link_to 'Edit', edit_article_path(article) %> </td>
    <td> <%= link_to 'Show', article_path(article) %> </td>
    <td> <%= link_to 'Delete', article_path(article),
      method: :delete, data: {confirm: "Are you sure?"} %> </td>    
  </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1 align="center">Create new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="center_text show-container">Title: <%= @article.title %> </h2>

<div class="well col-sm-8 center_obj">
  <h4 class="center_text"><strong>Description</strong></h4>
  <hr>
  <%= simple_format(@article.description) %>
  <hr>
  <div class="article-actions">
    <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete Article", article_path(@article), method: :delete,
    data: {confirm: "Are you sure you want to delete the article?"},
     class: "btn btn-xs btn-danger" %>
    <%= link_to "View All Articles", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="row">
    <div class="col-sm-6">
      <p>Copyright 2020 Alpha Blog</p>
    </div>
    <div class="col-sm-6 footer-right">
      <%= link_to "About", about_path %>
    </div>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-sm-10">
    <% flash.each do |name, msg| %>
    <div class='alert alert-<%="#{name}" %>'>
      <a href="#" class="close" data-dismiss="alert">&#215;
      </a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom">

  <!-- convert commented out html line below to embedded ruby -->
  <!-- <a class="navbar-brand logo" href="#">Alpha Blog</a> -->
  <%= link_to "Alpha Blog", root_path, class: "navbar-brand logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <!-- <a class="nav-link" href="#">Articles</a> -->
        <%= link_to "Articles", articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Actions
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <!-- <a class="dropdown-item" href="#">New Article</a> -->
          <%= link_to "New Article", new_article_path, class: "dropdown-item" %>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestAppAlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
      <!-- <div class="container"> -->
    <%= yield %>
    <%= render 'layouts/footer' %>
      <!-- </div> -->
    </body>
  </html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1 class="display-4 jumbotext">Alpha Blog</h1>
  <%= link_to "Sign Up Now", "#", class: "btn signup btn-lg" %>
  <!-- <a class="btn btn-signup btn-lg" href="#" role="button">Sign Up Now</a> -->
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
  <div class="col-sm-8">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
          Update the following
          <%= pluralize(obj.errors.count, "error")%>
           in order to save the article:
        </h2>
        <div class="panel-body">
          <ul>
            <% obj.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>